//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        public string suplno { get; set; }
        public string suplname { get; set; }
        public string supladdr { get; set; }
    }
}
